### ISSUE TITLE
activesitesonly parameter does not work

### ISSUE THREAD

**Issue by scorpwarp23** [Semantics3/semantics3-node#5]
Hi,

Whether I use this parameter in the playground or via CURL or via this package, I still get results with an empty "sitedetails" array. What gives?

**Comment by gc20** [comment]
Hi there,
The sitedetails array may be empty either because:
1. You haven't used the "activeproductsonly" query, as a result of which the product in question has no active sites to show.
2. You're on the free/starter plan, as a result of which your access to data is limited.
